version: '3.1'
services:
  test.work:
    image: test-work:latest
    container_name: test-work
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opts/app/.env
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db